# Generated by Django 3.1.4 on 2021-11-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default='no bio...', max_length=300),
        ),
        migrations.AddField(
            model_name='author',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(choices=[('KG', 'Kyrgyzstan'), ('KZ', 'Kazakstan'), ('UZ', 'Uzbekistan'), ('TJ', 'Tajikistan'), ('RU', 'Russia'), ('CHN', 'China')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
